// Package web provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package web

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AuthConfigApiKeyIn.
const (
	Header AuthConfigApiKeyIn = "header"
	Query  AuthConfigApiKeyIn = "query"
)

// Valid indicates whether the value is a known member of the AuthConfigApiKeyIn enum.
func (e AuthConfigApiKeyIn) Valid() bool {
	switch e {
	case Header:
		return true
	case Query:
		return true
	default:
		return false
	}
}

// Defines values for AuthConfigType.
const (
	ApiKey    AuthConfigType = "apiKey"
	Basic     AuthConfigType = "basic"
	Bearer    AuthConfigType = "bearer"
	JwtBearer AuthConfigType = "jwtBearer"
	None      AuthConfigType = "none"
)

// Valid indicates whether the value is a known member of the AuthConfigType enum.
func (e AuthConfigType) Valid() bool {
	switch e {
	case ApiKey:
		return true
	case Basic:
		return true
	case Bearer:
		return true
	case JwtBearer:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for JsonRpcRequestJsonrpc.
const (
	JsonRpcRequestJsonrpcN20 JsonRpcRequestJsonrpc = "2.0"
)

// Valid indicates whether the value is a known member of the JsonRpcRequestJsonrpc enum.
func (e JsonRpcRequestJsonrpc) Valid() bool {
	switch e {
	case JsonRpcRequestJsonrpcN20:
		return true
	default:
		return false
	}
}

// Defines values for JsonRpcRequestMethod.
const (
	Initialize               JsonRpcRequestMethod = "initialize"
	Notificationsinitialized JsonRpcRequestMethod = "notifications/initialized"
	Toolscall                JsonRpcRequestMethod = "tools/call"
	Toolslist                JsonRpcRequestMethod = "tools/list"
)

// Valid indicates whether the value is a known member of the JsonRpcRequestMethod enum.
func (e JsonRpcRequestMethod) Valid() bool {
	switch e {
	case Initialize:
		return true
	case Notificationsinitialized:
		return true
	case Toolscall:
		return true
	case Toolslist:
		return true
	default:
		return false
	}
}

// Defines values for JsonRpcResponseJsonrpc.
const (
	JsonRpcResponseJsonrpcN20 JsonRpcResponseJsonrpc = "2.0"
)

// Valid indicates whether the value is a known member of the JsonRpcResponseJsonrpc enum.
func (e JsonRpcResponseJsonrpc) Valid() bool {
	switch e {
	case JsonRpcResponseJsonrpcN20:
		return true
	default:
		return false
	}
}

// Defines values for ServerTransport.
const (
	ServerTransportHttp  ServerTransport = "http"
	ServerTransportSse   ServerTransport = "sse"
	ServerTransportStdio ServerTransport = "stdio"
)

// Valid indicates whether the value is a known member of the ServerTransport enum.
func (e ServerTransport) Valid() bool {
	switch e {
	case ServerTransportHttp:
		return true
	case ServerTransportSse:
		return true
	case ServerTransportStdio:
		return true
	default:
		return false
	}
}

// Defines values for ServerStatusTransport.
const (
	ServerStatusTransportHttp  ServerStatusTransport = "http"
	ServerStatusTransportSse   ServerStatusTransport = "sse"
	ServerStatusTransportStdio ServerStatusTransport = "stdio"
)

// Valid indicates whether the value is a known member of the ServerStatusTransport enum.
func (e ServerStatusTransport) Valid() bool {
	switch e {
	case ServerStatusTransportHttp:
		return true
	case ServerStatusTransportSse:
		return true
	case ServerStatusTransportStdio:
		return true
	default:
		return false
	}
}

// APIKey defines model for APIKey.
type APIKey struct {
	CreatedAt   *string  `json:"createdAt,omitempty"`
	Enabled     bool     `json:"enabled"`
	EndpointIds []string `json:"endpointIds"`
	Id          string   `json:"id"`
	Name        string   `json:"name"`
	UpdatedAt   *string  `json:"updatedAt,omitempty"`

	// Value Secret API key value. Returned only on write requests, never in list responses.
	Value string `json:"value"`
}

// APIKeyStatus defines model for APIKeyStatus.
type APIKeyStatus struct {
	CreatedAt   *string  `json:"createdAt,omitempty"`
	Enabled     bool     `json:"enabled"`
	EndpointIds []string `json:"endpointIds"`
	HasValue    bool     `json:"hasValue"`
	Id          string   `json:"id"`
	Name        string   `json:"name"`
	UpdatedAt   *string  `json:"updatedAt,omitempty"`
}

// APIKeysResponse defines model for APIKeysResponse.
type APIKeysResponse struct {
	ApiKeys []APIKeyStatus `json:"apiKeys"`
}

// AuthConfig defines model for AuthConfig.
type AuthConfig struct {
	ApiKeyIn    *AuthConfigApiKeyIn `json:"apiKeyIn,omitempty"`
	ApiKeyName  *string             `json:"apiKeyName,omitempty"`
	ApiKeyValue *string             `json:"apiKeyValue,omitempty"`
	Password    *string             `json:"password,omitempty"`
	Token       *string             `json:"token,omitempty"`
	Type        *AuthConfigType     `json:"type,omitempty"`
	Username    *string             `json:"username,omitempty"`
}

// AuthConfigApiKeyIn defines model for AuthConfig.ApiKeyIn.
type AuthConfigApiKeyIn string

// AuthConfigType defines model for AuthConfig.Type.
type AuthConfigType string

// CallToolRequest defines model for CallToolRequest.
type CallToolRequest struct {
	Arguments *map[string]interface{} `json:"arguments,omitempty"`
}

// CallToolResult defines model for CallToolResult.
type CallToolResult struct {
	Content *[]map[string]interface{} `json:"content,omitempty"`
	IsError *bool                     `json:"isError,omitempty"`
}

// ConfigResponse defines model for ConfigResponse.
type ConfigResponse struct {
	Path string `json:"path"`
}

// Endpoint defines model for Endpoint.
type Endpoint struct {
	CreatedAt   *string    `json:"createdAt,omitempty"`
	Description *string    `json:"description,omitempty"`
	Enabled     bool       `json:"enabled"`
	Id          string     `json:"id"`
	Name        string     `json:"name"`
	RateLimit   *RateLimit `json:"rateLimit,omitempty"`
	ServerIds   []string   `json:"serverIds"`
	UpdatedAt   *string    `json:"updatedAt,omitempty"`
}

// EndpointStatus defines model for EndpointStatus.
type EndpointStatus struct {
	CreatedAt   *string       `json:"createdAt,omitempty"`
	Description *string       `json:"description,omitempty"`
	Enabled     bool          `json:"enabled"`
	Id          string        `json:"id"`
	Name        string        `json:"name"`
	RateLimit   *RateLimit    `json:"rateLimit,omitempty"`
	ServerIds   []string      `json:"serverIds"`
	UpdatedAt   *string       `json:"updatedAt,omitempty"`
	Usage       UsageSnapshot `json:"usage"`
}

// EndpointsResponse defines model for EndpointsResponse.
type EndpointsResponse struct {
	Endpoints []EndpointStatus `json:"endpoints"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Ok        bool      `json:"ok"`
	Timestamp time.Time `json:"timestamp"`
}

// JsonRpcError defines model for JsonRpcError.
type JsonRpcError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// JsonRpcID defines model for JsonRpcID.
type JsonRpcID struct {
	union json.RawMessage
}

// JsonRpcID0 defines model for .
type JsonRpcID0 = string

// JsonRpcID1 defines model for .
type JsonRpcID1 = int

// JsonRpcID2 defines model for .
type JsonRpcID2 = float32

// JsonRpcRequest defines model for JsonRpcRequest.
type JsonRpcRequest struct {
	Id      *JsonRpcID              `json:"id,omitempty"`
	Jsonrpc JsonRpcRequestJsonrpc   `json:"jsonrpc"`
	Method  JsonRpcRequestMethod    `json:"method"`
	Params  *map[string]interface{} `json:"params,omitempty"`
}

// JsonRpcRequestJsonrpc defines model for JsonRpcRequest.Jsonrpc.
type JsonRpcRequestJsonrpc string

// JsonRpcRequestMethod defines model for JsonRpcRequest.Method.
type JsonRpcRequestMethod string

// JsonRpcResponse defines model for JsonRpcResponse.
type JsonRpcResponse struct {
	Error   *JsonRpcError           `json:"error,omitempty"`
	Id      *JsonRpcID              `json:"id,omitempty"`
	Jsonrpc JsonRpcResponseJsonrpc  `json:"jsonrpc"`
	Result  *map[string]interface{} `json:"result,omitempty"`
}

// JsonRpcResponseJsonrpc defines model for JsonRpcResponse.Jsonrpc.
type JsonRpcResponseJsonrpc string

// RateLimit defines model for RateLimit.
type RateLimit struct {
	RequestsPerMinute *int `json:"requestsPerMinute,omitempty"`
}

// Server defines model for Server.
type Server struct {
	Args      *[]string          `json:"args,omitempty"`
	Auth      *AuthConfig        `json:"auth,omitempty"`
	Command   *string            `json:"command,omitempty"`
	CreatedAt *string            `json:"createdAt,omitempty"`
	Enabled   bool               `json:"enabled"`
	Env       *map[string]string `json:"env,omitempty"`
	Headers   *map[string]string `json:"headers,omitempty"`
	Id        string             `json:"id"`
	Name      string             `json:"name"`
	Transport *ServerTransport   `json:"transport,omitempty"`
	UpdatedAt *string            `json:"updatedAt,omitempty"`
	Url       *string            `json:"url,omitempty"`
	Weight    int                `json:"weight"`
}

// ServerTransport defines model for Server.Transport.
type ServerTransport string

// ServerStatus defines model for ServerStatus.
type ServerStatus struct {
	Args      *[]string              `json:"args,omitempty"`
	Auth      *AuthConfig            `json:"auth,omitempty"`
	Command   *string                `json:"command,omitempty"`
	CreatedAt *string                `json:"createdAt,omitempty"`
	Enabled   bool                   `json:"enabled"`
	Env       *map[string]string     `json:"env,omitempty"`
	Headers   *map[string]string     `json:"headers,omitempty"`
	Id        string                 `json:"id"`
	Name      string                 `json:"name"`
	Status    Status                 `json:"status"`
	Transport *ServerStatusTransport `json:"transport,omitempty"`
	UpdatedAt *string                `json:"updatedAt,omitempty"`
	Url       *string                `json:"url,omitempty"`
	Usage     UsageSnapshot          `json:"usage"`
	Weight    int                    `json:"weight"`
}

// ServerStatusTransport defines model for ServerStatus.Transport.
type ServerStatusTransport string

// ServersResponse defines model for ServersResponse.
type ServersResponse struct {
	Servers []ServerStatus `json:"servers"`
}

// Status defines model for Status.
type Status struct {
	Error   *string `json:"error,omitempty"`
	Running bool    `json:"running"`
}

// TestResult defines model for TestResult.
type TestResult struct {
	Ok        bool      `json:"ok"`
	Status    string    `json:"status"`
	ToolCount int       `json:"toolCount"`
	Tools     *[]string `json:"tools,omitempty"`
}

// TestServerErrorResponse defines model for TestServerErrorResponse.
type TestServerErrorResponse struct {
	Error  string     `json:"error"`
	Result TestResult `json:"result"`
}

// TestServerResponse defines model for TestServerResponse.
type TestServerResponse struct {
	Result TestResult `json:"result"`
}

// Tool defines model for Tool.
type Tool struct {
	CreatedAt   *string                 `json:"createdAt,omitempty"`
	Description *string                 `json:"description,omitempty"`
	InputSchema *map[string]interface{} `json:"inputSchema,omitempty"`
	Name        string                  `json:"name"`
	NativeName  string                  `json:"nativeName"`
	ServerId    string                  `json:"serverId"`
	ServerName  string                  `json:"serverName"`
	UpdatedAt   *string                 `json:"updatedAt,omitempty"`
}

// ToolsErrorResponse defines model for ToolsErrorResponse.
type ToolsErrorResponse struct {
	Error string `json:"error"`
	Tools []Tool `json:"tools"`
}

// ToolsResponse defines model for ToolsResponse.
type ToolsResponse struct {
	Tools []Tool `json:"tools"`
}

// UsageSnapshot defines model for UsageSnapshot.
type UsageSnapshot struct {
	CurrentWindowCalls  int     `json:"currentWindowCalls"`
	FailedCalls         int64   `json:"failedCalls"`
	LastCalledAt        *string `json:"lastCalledAt,omitempty"`
	LastError           *string `json:"lastError,omitempty"`
	LimitPerMinute      int     `json:"limitPerMinute"`
	RateLimitedCalls    int64   `json:"rateLimitedCalls"`
	RemainingThisMinute int     `json:"remainingThisMinute"`
	SuccessfulCalls     int64   `json:"successfulCalls"`
	TotalCalls          int64   `json:"totalCalls"`
	WindowResetAt       *string `json:"windowResetAt,omitempty"`
}

// EndpointID defines model for EndpointID.
type EndpointID = string

// ID defines model for ID.
type ID = string

// ToolName defines model for ToolName.
type ToolName = string

// RestError defines model for RestError.
type RestError = ErrorResponse

// UpsertAPIKeyJSONRequestBody defines body for UpsertAPIKey for application/json ContentType.
type UpsertAPIKeyJSONRequestBody = APIKey

// UpsertEndpointJSONRequestBody defines body for UpsertEndpoint for application/json ContentType.
type UpsertEndpointJSONRequestBody = Endpoint

// CallEndpointToolJSONRequestBody defines body for CallEndpointTool for application/json ContentType.
type CallEndpointToolJSONRequestBody = CallToolRequest

// UpsertServerJSONRequestBody defines body for UpsertServer for application/json ContentType.
type UpsertServerJSONRequestBody = Server

// TestServerJSONRequestBody defines body for TestServer for application/json ContentType.
type TestServerJSONRequestBody = Server

// CallGlobalToolJSONRequestBody defines body for CallGlobalTool for application/json ContentType.
type CallGlobalToolJSONRequestBody = CallToolRequest

// McpGlobalJSONRequestBody defines body for McpGlobal for application/json ContentType.
type McpGlobalJSONRequestBody = JsonRpcRequest

// McpEndpointJSONRequestBody defines body for McpEndpoint for application/json ContentType.
type McpEndpointJSONRequestBody = JsonRpcRequest

// AsJsonRpcID0 returns the union data inside the JsonRpcID as a JsonRpcID0
func (t JsonRpcID) AsJsonRpcID0() (JsonRpcID0, error) {
	var body JsonRpcID0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJsonRpcID0 overwrites any union data inside the JsonRpcID as the provided JsonRpcID0
func (t *JsonRpcID) FromJsonRpcID0(v JsonRpcID0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJsonRpcID0 performs a merge with any union data inside the JsonRpcID, using the provided JsonRpcID0
func (t *JsonRpcID) MergeJsonRpcID0(v JsonRpcID0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJsonRpcID1 returns the union data inside the JsonRpcID as a JsonRpcID1
func (t JsonRpcID) AsJsonRpcID1() (JsonRpcID1, error) {
	var body JsonRpcID1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJsonRpcID1 overwrites any union data inside the JsonRpcID as the provided JsonRpcID1
func (t *JsonRpcID) FromJsonRpcID1(v JsonRpcID1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJsonRpcID1 performs a merge with any union data inside the JsonRpcID, using the provided JsonRpcID1
func (t *JsonRpcID) MergeJsonRpcID1(v JsonRpcID1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJsonRpcID2 returns the union data inside the JsonRpcID as a JsonRpcID2
func (t JsonRpcID) AsJsonRpcID2() (JsonRpcID2, error) {
	var body JsonRpcID2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJsonRpcID2 overwrites any union data inside the JsonRpcID as the provided JsonRpcID2
func (t *JsonRpcID) FromJsonRpcID2(v JsonRpcID2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJsonRpcID2 performs a merge with any union data inside the JsonRpcID, using the provided JsonRpcID2
func (t *JsonRpcID) MergeJsonRpcID2(v JsonRpcID2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t JsonRpcID) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *JsonRpcID) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
