apiVersion: v1
kind: Secret
metadata:
  name: mcp-app-secret
type: Opaque
stringData:
  MCP_GATEWAY_ADMIN_EMAIL: admin@gmail.com 
  MCP_GATEWAY_ADMIN_PASSWORD: cHJvZA== 
  MCP_GATEWAY_JWT_SECRET: cHJvZA==